[ 'waitForTime', '16:29:00' ],
[ 'play', 0, 'b29 - 29,59 (20m) boarding countdown.wav' ],
[ 'waitForTime', '16:34:00' ],
[ 'play', 0, 'b34 - 34,04 (15m) boarding countdown.wav' ],
[ 'waitForTime', '16:39:00' ],
[ 'play', 0, 'b29 - 39,09 (10m) boarding countdown.wav' ],
[ 'waitForTime', '16:44:00' ],
[ 'play', 0, 'b44 - 44,14 (5m) boarding countdown.wav' ],
[ 'waitForTime', '16:46:00' ],
[ 'play', 0, 'b46 - 46,16 (3m) boarding countdown.wav' ],
[ 'waitForTime', '16:47:00' ],
[ 'play', 0, 'b47 - 47,17 (2m) boarding countdown.wav' ],
[ 'waitForTime', '16:48:00' ],
[ 'play', 0, 'b48 - 48,18 (1m) boarding countdown.wav' ],
[ 'waitForTime', '16:49:00' ],
[ 'play', 0, 'c01 - When Christmas Comes to Town.wav' ],
[ 'waitForTrackEnd', 0 ],

[ 'play', 0, 'c02 - Spirit of the Season.wav' ],
[ 'waitForTrackEnd', 0 ],
[ 'play', 0, 'c03 - Seeing is Believing.wav' ],
[ 'waitForTrackEnd', 0 ],
[ 'play', 0, 'c04 - The Polar Express.wav' ],
[ 'waitForTrackEnd', 0 ],
[ 'play', 0, 'c04a - Good evening and welcome aboard.wav' ],
[ 'waitForTrackEnd', 0 ],
[ 'play', 0, 'c05 - Hot Chocolate (1).wav' ],
[ 'waitForTrackEnd', 0 ],
[ 'play', 0, 'c05a - I dont think everybody has had hot chocolate yet.wav' ],
[ 'waitForTrackEnd', 0 ],
[ 'play', 0, 'c05b - 5s pause.wav' ],
[ 'waitForTrackEnd', 0 ],
[ 'play', 0, 'c06 - Hot Chocolate (2).wav' ],
[ 'waitForTrackEnd', 0 ],
[ 'play', 0, 'c06a - And now lets hear the story of the Polar Express.wav' ],
[ 'waitForTrackEnd', 0 ],

[ 'play', 0, 'c07 - (Book Reading).wav' ],
// [ 'waitForTrackEnd', 0 ],
[ 'waitFor', 'frontWolfTrigger' ],
[ 'play', 1, 'a07a - Hungry wolves.wav' ]
[ 'waitFor', 'frontGlacierTrigger' ],
[ 'play', 1, 'a07b - Glacier Gulch.wav' ]
[ 'waitFor', 'backWolfTrigger' ],
[ 'play', 2, 'a07a - Hungry wolves.wav' ]
[ 'waitFor', 'backGlacierTrigger' ],
[ 'play', 2, 'a07b - Glacier Gulch.wav' ]


[ 'play', 0, 'c08 - Santa Claus is Coming to Town.wav' ],
a08a - As we round the bend (North Pole).wav
a08b - The elves are out this evening.wav
[ 'waitForTrackEnd', 0 ],
[ 'waitFor', 'stopped' ],
[ 'play', 0, 'c08a - Brief station stop.wav' ],
[ 'waitForTrackEnd', 0 ],
[ 'waitFor', 'moving' ],
[ 'play', 0, 'c09 - Believe (1).wav' ],
[ 'waitForTrackEnd', 0 ],
[ 'play', 0, 'c10 - We Wish You a Merry Christmas (1).wav' ],
[ 'waitForTrackEnd', 0 ],
[ 'waitFor', 'stopped' ],
[ 'play', 0, 'c10a - Thousands of caribou.wav' ],
[ 'waitForTrackEnd', 0 ],
[ 'waitFor', 'moving' ],
[ 'play', 0, 'c11 - Rudolph the Red-Nosed Reindeer.wav' ],
[ 'waitForTrackEnd', 0 ],
[ 'play', 0, 'c12 - Frosty the Snowman.wav' ],
[ 'waitForTrackEnd', 0 ],
[ 'play', 0, 'c13 - Believe (2).wav' ],
[ 'waitForTrackEnd', 0 ],
[ 'play', 0, 'c14 - We Wish You a Merry Christmas (2).wav' ],
[ 'waitForTrackEnd', 0 ],
[ 'play', 0, 'c14a - Please join us in singing.wav' ],
[ 'waitForTrackEnd', 0 ],
[ 'play', 0, 'c15 - Twelve Days of Christmas.wav' ],
[ 'waitForTrackEnd', 0 ],
[ 'play', 0, 'c16 - Holly Jolly Christmas.wav' ],
[ 'waitForTrackEnd', 0 ],
[ 'play', 0, 'c16a - And now for our final number.wav' ],
[ 'waitForTrackEnd', 0 ],
[ 'play', 0, "c17 - Rockin' Around the Christmas Tree.wav" ],
[ 'waitForTrackEnd', 0 ],
[ 'play', 0, 'c17a - (AIM) Closing comments.wav' ],
[ 'waitForTrackEnd', 0 ],
[ 'play', 0, 'c17a - (DDS) Closing comments.wav' ],
[ 'waitForTrackEnd', 0 ],
[ 'play', 0, 'c18 - Suite from The Polar Express.wav' ],
[ 'waitForTrackEnd', 0 ],
